'use client'

import Link from 'next/link'
import { useParams, useRouter } from 'next/navigation'
import { useEffect, useState } from 'react'
import { ArrowLeft, Save, Trash2, Shield, Camera, Users, Trophy } from 'lucide-react'
import { db } from '../../../src/lib/storage/db'
import { fileToOptimizedDataUrl } from '../../../src/lib/media/image'
import type { Club, Player, PlayerTeamSeason, Season, Team } from '../../../src/lib/storage/types'
import '../../dashboard.css'

export default function TeamDetailPage() {
  const params = useParams<{ id: string }>(); const router = useRouter(); const id = params.id
  const [team, setTeam] = useState<Team | null>(null); const [club, setClub] = useState<Club | null>(null); const [players, setPlayers] = useState<Player[]>([]); const [relations, setRelations] = useState<PlayerTeamSeason[]>([]); const [seasons, setSeasons] = useState<Season[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
  async function load() { if (!db) return; setLoading(true); const current = await db.teams.get(id); if (!current) { setTeam(null); setLoading(false); return }; const [nextClub, nextRelations, nextPlayers, nextSeasons] = await Promise.all([db.clubs.get(current.clubId), db.playerTeamSeasons.where('teamId').equals(id).toArray(), db.players.toArray(), db.seasons.orderBy('name').reverse().toArray()]); setTeam(current); setClub(nextClub ?? null); setRelations(nextRelations); setPlayers(nextPlayers); setSeasons(nextSeasons); setLoading(false) }
  useEffect(() => { void load() }, [id])
  async function save() { if (!db || !team) return; setSaving(true); try { await db.teams.update(team.id, { name: team.name.trim(), category: team.category.trim(), logoPath: team.logoPath, updatedAt: new Date().toISOString() }); await load() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível guardar a equipa.') } finally { setSaving(false) } }
  async function changeLogo(file?: File) { if (!file || !team) return; try { setTeam(current => current ? { ...current, logoPath: '' } : current); const logoPath = await fileToOptimizedDataUrl(file, 600, .9); setTeam(current => current ? { ...current, logoPath } : current) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível carregar o logótipo.') } }
  async function remove() { if (!db || !team || !window.confirm(`Eliminar ${team.name}?`)) return; await db.teams.delete(team.id); router.push('/teams') }
  if (loading) return <main className="content standalonePage"><p>A carregar equipa…</p></main>
  if (!team) return <main className="content standalonePage"><p>Equipa não encontrada.</p><Link href="/teams">Voltar às equipas</Link></main>
  const initials = team.name.split(' ').filter(Boolean).slice(0,2).map(x => x[0]).join('').toUpperCase(); const linkedPlayers = relations.map(relation => ({ relation, player: players.find(item => item.id === relation.playerId), season: seasons.find(item => item.id === relation.seasonId) })).filter(item => item.player)
  return <main className="content standalonePage">
    <header className="topbar"><Link href="/teams" className="backLink"><ArrowLeft size={16}/> Equipas</Link><div className="topbarActions"><button onClick={() => void save()} disabled={saving}><Save size={17}/> {saving ? 'A guardar…' : 'Guardar'}</button><button className="dangerButton" onClick={() => void remove()}><Trash2 size={17}/> Eliminar</button></div></header>
    {error && <div className="errorState">{error}</div>}
    <section className="teamHero"><div>{team.logoPath ? <img className="teamLogo" src={team.logoPath} alt={`Logótipo ${team.name}`}/> : <div className="teamLogoFallback">{initials || 'EQ'}</div>}<div className="logoPicker"><label><Camera size={14}/> Alterar logótipo<input type="file" accept="image/*" onChange={e => void changeLogo(e.target.files?.[0])}/></label></div></div><div><span className="eyebrow">FICHA DE EQUIPA · ANDEBOL</span><h1>{team.name}</h1><div className="playerMeta"><span>{club?.name ?? 'Clube'}</span><span>{team.category}</span><span>{team.gender === 'F' ? 'Feminino' : team.gender === 'M' ? 'Masculino' : 'Misto'}</span></div><p>Identidade da equipa, plantel e contexto competitivo.</p><div className="localForm" style={{marginTop:18,background:'rgba(255,255,255,.06)',borderColor:'rgba(255,255,255,.12)'}}><input value={team.name} onChange={e => setTeam(current => current ? {...current,name:e.target.value}:current)} aria-label="Nome da equipa"/><input value={team.category} onChange={e => setTeam(current => current ? {...current,category:e.target.value}:current)} aria-label="Categoria"/></div></div></section>
    <section className="section"><div className="sectionHeader"><div><h2>Plantel</h2><p>Atletas associados a esta equipa e respetiva época.</p></div><Users size={24}/></div><div className="localList">{linkedPlayers.length === 0 && <div className="emptyState"><strong>Sem atletas associadas</strong><span>Adiciona atletas e liga-as a esta equipa.</span></div>}{linkedPlayers.map(({relation,player,season}) => <Link href={`/players/${player!.id}`} className="localRow" key={relation.id} style={{textDecoration:'none',color:'inherit'}}><div style={{display:'flex',alignItems:'center',gap:12}}>{player!.photoPath ? <img className="miniLogo" src={player!.photoPath} alt=""/> : <span className="avatar">{player!.displayName.slice(0,1)}</span>}<div><strong>{player!.displayName}</strong><span>{relation.position ?? player!.position ?? 'Sem posição'} · {season?.name ?? 'Sem época'}{relation.shirtNumber ? ` · #${relation.shirtNumber}` : ''}</span></div></div>{player!.hpi ? <span><strong>HPI {player!.hpi.score}</strong></span> : null}</Link>)}</div></section>
    <section className="section"><div className="sectionHeader"><div><h2>Identidade competitiva</h2><p>Base para a futura análise coletiva e scouting.</p></div><Trophy size={24}/></div><div className="explorerGrid"><div className="explorerCard"><span>Atletas</span><strong>{linkedPlayers.length}</strong><small>Relações de plantel</small></div><div className="explorerCard"><span>Épocas</span><strong>{new Set(relations.map(item => item.seasonId)).size}</strong><small>Épocas com atletas associadas</small></div><div className="explorerCard"><span>Clube</span><strong>{club?.shortName ?? '—'}</strong><small>{club?.name ?? 'Não definido'}</small></div><div className="explorerCard"><span>HPI médio</span><strong>{linkedPlayers.filter(item => item.player?.hpi).length ? Math.round(linkedPlayers.reduce((sum,item)=>sum+(item.player?.hpi?.score ?? 0),0)/linkedPlayers.filter(item=>item.player?.hpi).length) : '—'}</strong><small>Atletas com HPI recebido</small></div></div></section>
  </main>
}
