import type { HandballPerformanceDB } from '../storage/db';
import type { MatchEvent } from '../storage/types';

export const PRE_MATCH_STATS_VERSION = '1.1.0';
type MetricSet={matches:number;goals:number;shots:number;shotGoals:number;shotMisses:number;saves:number;assists:number;turnovers:number;yellow:number;twoMin:number;red:number};
export type PreMatchPlayerStats=MetricSet&{playerId:string;name:string;position?:string;shirtNumber?:number;seasonMatches:number;last5:MetricSet;last10:MetricSet};
export type PreMatchSplit=MetricSet&{goalsForPerMatch:number;goalsAgainstPerMatch:number};
export type PreMatchStats={version:typeof PRE_MATCH_STATS_VERSION;generatedAt:string;currentMatchId:string;scope:{seasonId:string;teamId:string;competitionId?:string|null;homeAway:'HOME'|'AWAY'|'NEUTRAL'};availableCompetitions:Array<{id:string;name:string}>;team:MetricSet&{teamId:string;seasonId:string;goalsForPerMatch:number;goalsAgainstPerMatch:number;last5:MetricSet;last10:MetricSet};splits:{all:PreMatchSplit;home:PreMatchSplit;away:PreMatchSplit;currentCompetition:PreMatchSplit};players:PreMatchPlayerStats[]};
const empty=():MetricSet=>({matches:0,goals:0,shots:0,shotGoals:0,shotMisses:0,saves:0,assists:0,turnovers:0,yellow:0,twoMin:0,red:0});
function add(m:MetricSet,e:MatchEvent,teamId:string){if(e.teamId!==teamId)return;const t=String(e.type||'').toLowerCase(),r=String(e.result||'').toLowerCase();if(t==='goal'||t==='golo'){m.goals++;m.shotGoals++;m.shots++;}if(t.includes('shot')||t.includes('remate')||t.includes('throw')||t.includes('7m')){if(t!=='goal'&&t!=='golo')m.shots++;if(['goal','golo','scored'].includes(r))m.shotGoals++;if(['miss','saved','falhado','defended'].includes(r))m.shotMisses++;}if(t.includes('assist'))m.assists++;if(t.includes('turnover')||t.includes('loss')||t.includes('perda'))m.turnovers++;if(t.includes('yellow')||t.includes('amarelo'))m.yellow++;if(t.includes('2min')||t.includes('two')||t.includes('exclusion')||t.includes('exclus'))m.twoMin++;if(t.includes('red')||t.includes('vermelho'))m.red++;if(t.includes('save')||t.includes('defesa'))m.saves++;}
function metrics(events:MatchEvent[],teamId:string):MetricSet{const m=empty();events.forEach(e=>add(m,e,teamId));m.matches=new Set(events.map(e=>e.matchId)).size;return m;}
function split(ms:any[],events:MatchEvent[],teamId:string):PreMatchSplit{const ids=new Set(ms.map(m=>m.id)),m=metrics(events.filter(e=>ids.has(e.matchId)),teamId);const gf=ms.reduce((s,x)=>s+(x.goalsFor??0),0),ga=ms.reduce((s,x)=>s+(x.goalsAgainst??0),0);return {...m,goalsForPerMatch:ms.length?gf/ms.length:0,goalsAgainstPerMatch:ms.length?ga/ms.length:0};}
export async function buildPreMatchStats(db:HandballPerformanceDB,matchId:string):Promise<PreMatchStats>{const match=await db.matches.get(matchId);if(!match)throw new Error('MATCH_NOT_FOUND');const[players,squads,matches,events,competitions]=await Promise.all([db.players.toArray(),db.matchSquads.where('matchId').equals(matchId).toArray(),db.matches.where('teamId').equals(match.teamId).toArray(),db.events.toArray(),db.competitions.toArray()]);const prev=matches.filter(x=>x.id!==matchId&&x.status==='COMPLETED'&&new Date(x.date)<new Date(match.date)).sort((a,b)=>new Date(a.date).getTime()-new Date(b.date).getTime());const ids=new Set(prev.map(x=>x.id)),hist=events.filter(e=>ids.has(e.matchId)),last5=prev.slice(-5),last10=prev.slice(-10),pids=new Set(squads.map(x=>x.playerId));const playerStats=players.filter(p=>pids.has(p.id)).map(p=>{const pe=hist.filter(e=>e.playerId===p.id),s=squads.find(x=>x.playerId===p.id);return{...metrics(pe,match.teamId),playerId:p.id,name:p.displayName,position:s?.position??p.position,shirtNumber:s?.shirtNumber??p.shirtNumber,seasonMatches:new Set(pe.map(e=>e.matchId)).size,last5:metrics(pe.filter(e=>new Set(last5.map(x=>x.id)).has(e.matchId)),match.teamId),last10:metrics(pe.filter(e=>new Set(last10.map(x=>x.id)).has(e.matchId)),match.teamId)}});const tm=metrics(hist,match.teamId),gf=prev.reduce((s,x)=>s+(x.goalsFor??0),0),ga=prev.reduce((s,x)=>s+(x.goalsAgainst??0),0),home=prev.filter(x=>x.homeAway==='HOME'),away=prev.filter(x=>x.homeAway==='AWAY'),comp=match.competitionId?prev.filter(x=>x.competitionId===match.competitionId):prev;return{version:PRE_MATCH_STATS_VERSION,generatedAt:new Date().toISOString(),currentMatchId:match.id,scope:{seasonId:match.seasonId,teamId:match.teamId,competitionId:match.competitionId??null,homeAway:match.homeAway==='AWAY'?'AWAY':match.homeAway==='NEUTRAL'?'NEUTRAL':'HOME'},availableCompetitions:competitions.map(c=>({id:c.id,name:c.name})),team:{...tm,teamId:match.teamId,seasonId:match.seasonId,goalsForPerMatch:prev.length?gf/prev.length:0,goalsAgainstPerMatch:prev.length?ga/prev.length:0,last5:metrics(hist.filter(e=>new Set(last5.map(x=>x.id)).has(e.matchId)),match.teamId),last10:metrics(hist.filter(e=>new Set(last10.map(x=>x.id)).has(e.matchId)),match.teamId)},splits:{all:split(prev,hist,match.teamId),home:split(home,hist,match.teamId),away:split(away,hist,match.teamId),currentCompetition:split(comp,hist,match.teamId)},players:playerStats};}
