import type { HandballPerformanceDB } from '../storage/db';
import type { DataSource, HpiSnapshot, MatchEvent } from '../storage/types';

export const PRE_MATCH_STATS_VERSION = '1.3.0';
type MetricKey='goals'|'shots'|'shotGoals'|'shotMisses'|'saves'|'assists'|'turnovers'|'yellow'|'twoMin'|'red';
type MetricSet={matches:number;goals:number;shots:number;shotGoals:number;shotMisses:number;saves:number;assists:number;turnovers:number;yellow:number;twoMin:number;red:number};
export type PreMatchPlayerStats=MetricSet&{playerId:string;name:string;position?:string;shirtNumber?:number;seasonMatches:number;last5:MetricSet;last10:MetricSet;hpi?:HpiSnapshot|null};
export type PreMatchSplit=MetricSet&{goalsForPerMatch:number;goalsAgainstPerMatch:number};
export type PreMatchStats={version:typeof PRE_MATCH_STATS_VERSION;generatedAt:string;currentMatchId:string;scope:{seasonId:string;teamId:string;competitionId?:string|null;homeAway:'HOME'|'AWAY'|'NEUTRAL'};availableCompetitions:Array<{id:string;name:string}>;team:MetricSet&{teamId:string;seasonId:string;goalsForPerMatch:number;goalsAgainstPerMatch:number;hpiAverage?:number|null;hpiPlayers:number;last5:MetricSet;last10:MetricSet};splits:{all:PreMatchSplit;home:PreMatchSplit;away:PreMatchSplit;currentCompetition:PreMatchSplit};players:PreMatchPlayerStats[]};
const empty=():MetricSet=>({matches:0,goals:0,shots:0,shotGoals:0,shotMisses:0,saves:0,assists:0,turnovers:0,yellow:0,twoMin:0,red:0});
const priority:Record<string,number>={MATCH_SHEET:0,MANUAL_STATS:1,ANDEBOL_STATS:2,VIDEO:3};
const sourceOf=(e:MatchEvent)=>String(e.source||'MATCH_SHEET');
function addOne(m:MetricSet,e:MatchEvent){const t=String(e.type||'').toLowerCase(),r=String(e.result||'').toLowerCase();if(t==='goal'||t==='golo'){m.goals++;m.shotGoals++;m.shots++;return}if(t.includes('shot')||t.includes('remate')||t.includes('throw')||t.includes('7m')){m.shots++;if(['goal','golo','scored','made'].includes(r))m.shotGoals++;if(['miss','saved','falhado','defended'].includes(r))m.shotMisses++;return}if(t.includes('assist'))m.assists++;if(t.includes('turnover')||t.includes('loss')||t.includes('perda'))m.turnovers++;if(t.includes('yellow')||t.includes('amarelo'))m.yellow++;if(t.includes('2min')||t.includes('two')||t.includes('exclusion')||t.includes('exclus'))m.twoMin++;if(t.includes('red')||t.includes('vermelho'))m.red++;if(t.includes('save')||t.includes('defesa'))m.saves++;}
function metricKey(e:MatchEvent):MetricKey|undefined{const t=String(e.type||'').toLowerCase(),r=String(e.result||'').toLowerCase();if(t==='goal'||t==='golo')return'goals';if(t.includes('shot')||t.includes('remate')||t.includes('throw')||t.includes('7m'))return r==='miss'||r==='saved'||r==='falhado'||r==='defended'?'shotMisses':'shots';if(t.includes('assist'))return'assists';if(t.includes('turnover')||t.includes('loss')||t.includes('perda'))return'turnovers';if(t.includes('yellow')||t.includes('amarelo'))return'yellow';if(t.includes('2min')||t.includes('two')||t.includes('exclusion')||t.includes('exclus'))return'twoMin';if(t.includes('red')||t.includes('vermelho'))return'red';if(t.includes('save')||t.includes('defesa'))return'saves';return undefined;}
function metrics(events:MatchEvent[],teamId:string):MetricSet{const m=empty();const byMatch=new Map<string,Map<MetricKey,MatchEvent[]>>();for(const e of events){if(e.teamId!==teamId)continue;const key=metricKey(e);if(!key)continue;const mm=byMatch.get(e.matchId)||new Map<MetricKey,MatchEvent[]>();const arr=mm.get(key)||[];arr.push(e);mm.set(key,arr);byMatch.set(e.matchId,mm);}for(const mm of byMatch.values())for(const [key,arr] of mm){const max=Math.max(...arr.map(e=>priority[sourceOf(e)]??0));const chosen=arr.filter(e=>(priority[sourceOf(e)]??0)===max);for(const e of chosen)addOne(m,e);}m.matches=byMatch.size;return m;}
function split(ms:any[],events:MatchEvent[],teamId:string):PreMatchSplit{const ids=new Set(ms.map(m=>m.id)),m=metrics(events.filter(e=>ids.has(e.matchId)),teamId);const gf=ms.reduce((s,x)=>s+(x.goalsFor??0),0),ga=ms.reduce((s,x)=>s+(x.goalsAgainst??0),0);return{...m,goalsForPerMatch:ms.length?gf/ms.length:0,goalsAgainstPerMatch:ms.length?ga/ms.length:0};}
export async function buildPreMatchStats(db:HandballPerformanceDB,matchId:string):Promise<PreMatchStats>{const match=await db.matches.get(matchId);if(!match)throw new Error('MATCH_NOT_FOUND');const[players,squads,matches,events,competitions]=await Promise.all([db.players.toArray(),db.matchSquads.where('matchId').equals(matchId).toArray(),db.matches.where('teamId').equals(match.teamId).toArray(),db.events.toArray(),db.competitions.toArray()]);const prev=matches.filter(x=>x.id!==matchId&&x.status==='COMPLETED'&&new Date(x.date)<new Date(match.date)).sort((a,b)=>new Date(a.date).getTime()-new Date(b.date).getTime());const ids=new Set(prev.map(x=>x.id)),hist=events.filter(e=>ids.has(e.matchId)),last5=prev.slice(-5),last10=prev.slice(-10),pids=new Set(squads.map(x=>x.playerId));const playerStats=players.filter(p=>pids.has(p.id)).map(p=>{const pe=hist.filter(e=>e.playerId===p.id),s=squads.find(x=>x.playerId===p.id);return{...metrics(pe,match.teamId),playerId:p.id,name:p.displayName,position:s?.position??p.position,shirtNumber:s?.shirtNumber??p.shirtNumber,seasonMatches:new Set(pe.map(e=>e.matchId)).size,last5:metrics(pe.filter(e=>new Set(last5.map(x=>x.id)).has(e.matchId)),match.teamId),last10:metrics(pe.filter(e=>new Set(last10.map(x=>x.id)).has(e.matchId)),match.teamId),hpi:p.hpi??null}});const tm=metrics(hist,match.teamId),gf=prev.reduce((s,x)=>s+(x.goalsFor??0),0),ga=prev.reduce((s,x)=>s+(x.goalsAgainst??0),0),home=prev.filter(x=>x.homeAway==='HOME'),away=prev.filter(x=>x.homeAway==='AWAY'),comp=match.competitionId?prev.filter(x=>x.competitionId===match.competitionId):prev;const hpiPlayers=playerStats.filter(p=>p.hpi&&Number.isFinite(p.hpi.score));const hpiAverage=hpiPlayers.length? hpiPlayers.reduce((s,p)=>s+p.hpi!.score,0)/hpiPlayers.length:null;return{version:PRE_MATCH_STATS_VERSION,generatedAt:new Date().toISOString(),currentMatchId:match.id,scope:{seasonId:match.seasonId,teamId:match.teamId,competitionId:match.competitionId??null,homeAway:match.homeAway==='AWAY'?'AWAY':match.homeAway==='NEUTRAL'?'NEUTRAL':'HOME'},availableCompetitions:competitions.map(c=>({id:c.id,name:c.name})),team:{...tm,teamId:match.teamId,seasonId:match.seasonId,goalsForPerMatch:prev.length?gf/prev.length:0,goalsAgainstPerMatch:prev.length?ga/prev.length:0,hpiAverage,hpiPlayers,last5:metrics(hist.filter(e=>new Set(last5.map(x=>x.id)).has(e.matchId)),match.teamId),last10:metrics(hist.filter(e=>new Set(last10.map(x=>x.id)).has(e.matchId)),match.teamId)},splits:{all:split(prev,hist,match.teamId),home:split(home,hist,match.teamId),away:split(away,hist,match.teamId),currentCompetition:split(comp,hist,match.teamId)},players:playerStats};}
