'use client'

import Link from 'next/link'
import { useParams, useRouter } from 'next/navigation'
import { useEffect, useState } from 'react'
import { ArrowLeft, Save, Trash2, UserRound, Camera, Shield, Activity } from 'lucide-react'
import { db } from '../../../src/lib/storage/db'
import { calculatePlayerStats, type PlayerStats } from '../../../src/lib/players/stats'
import { fileToOptimizedDataUrl } from '../../../src/lib/media/image'
import type { Player, PlayerTeamSeason, Position, Season, Team } from '../../../src/lib/storage/types'
import '../../dashboard.css'

const positions: Position[] = ['GR', 'PE', 'LE', 'CE', 'LD', 'PD', 'PIV']

export default function PlayerDetailPage() {
  const params = useParams<{ id: string }>(); const router = useRouter(); const id = params.id
  const [player, setPlayer] = useState<Player | null>(null); const [relations, setRelations] = useState<PlayerTeamSeason[]>([]); const [teams, setTeams] = useState<Team[]>([]); const [seasons, setSeasons] = useState<Season[]>([])
  const [stats, setStats] = useState<PlayerStats>({ matches: 0, starts: 0, events: 0, shots: 0, goals: 0, assists: 0, turnovers: 0, yellowCards: 0, redCards: 0 }); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('')

  async function load() { const database = db; if (!database) return; setLoading(true); setError(''); const [nextPlayer, nextRelations, nextTeams, nextSeasons, squads, events] = await Promise.all([database.players.get(id), database.playerTeamSeasons.where('playerId').equals(id).toArray(), database.teams.orderBy('name').toArray(), database.seasons.orderBy('name').reverse().toArray(), database.matchSquads.where('playerId').equals(id).toArray(), database.events.where('playerId').equals(id).toArray()]); setPlayer(nextPlayer ?? null); setRelations(nextRelations); setTeams(nextTeams); setSeasons(nextSeasons); setStats(calculatePlayerStats(squads, events)); setLoading(false) }
  useEffect(() => { void load() }, [id])
  function update<K extends keyof Player>(key: K, value: Player[K]) { setPlayer(current => current ? { ...current, [key]: value } : current) }
  async function save() { const database = db; if (!database || !player) return; if (!player.firstName.trim() || !player.lastName.trim()) { setError('Nome e apelido são obrigatórios.'); return } setSaving(true); setError(''); try { await database.players.update(player.id, { firstName: player.firstName.trim(), lastName: player.lastName.trim(), displayName: `${player.firstName.trim()} ${player.lastName.trim()}`, birthDate: player.birthDate || undefined, shirtNumber: player.shirtNumber, position: player.position, hand: player.hand, photoPath: player.photoPath, hpi: player.hpi, hpiHistory: player.hpiHistory, active: player.active, updatedAt: new Date().toISOString() }); await load() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível guardar o atleta.') } finally { setSaving(false) } }
  async function changePhoto(file?: File) { if (!file || !player) return; try { update('photoPath', await fileToOptimizedDataUrl(file, 720, .84)) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível carregar a fotografia.') } }
  async function remove() { const database = db; if (!database || !player || !window.confirm(`Apagar ${player.displayName}? Esta ação remove também as ligações a equipas e épocas.`)) return; await database.transaction('rw', [database.players, database.playerTeamSeasons], async () => { await database.players.delete(player.id); const linked = await database.playerTeamSeasons.where('playerId').equals(player.id).toArray(); if (linked.length) await database.playerTeamSeasons.bulkDelete(linked.map(item => item.id)) }); router.push('/players') }

  if (loading) return <main className="content standalonePage"><p>A carregar atleta…</p></main>
  if (!player) return <main className="content standalonePage"><p>Atleta não encontrada.</p><Link href="/players">Voltar aos jogadores</Link></main>
  const primaryRelation = relations[0]; const team = teams.find(item => item.id === primaryRelation?.teamId); const season = seasons.find(item => item.id === primaryRelation?.seasonId)
  const statItems = [['Jogos', stats.matches], ['Minutos', '—'], ['Golos', stats.goals], ['Assistências', stats.assists], ['Remates', stats.shots], ['Perdas', stats.turnovers]]
  const hpi = player.hpi; const hpiLabel = hpi?.label ?? (hpi ? 'Pontuação de ações · Andebol-Stats' : 'A aguardar dados do Andebol-Stats'); const hpiHistory = player.hpiHistory ?? []; const hpiTrend = hpiHistory.length >= 2 ? hpiHistory[hpiHistory.length - 1].score - hpiHistory[hpiHistory.length - 2].score : null
  const initials = player.displayName.split(' ').filter(Boolean).slice(0, 2).map(part => part[0]).join('').toUpperCase()

  return <main className="content standalonePage">
    <header className="topbar"><div><Link href="/players" className="backLink"><ArrowLeft size={16}/> Jogadores</Link></div><div className="topbarActions"><button onClick={() => void save()} disabled={saving}><Save size={17}/> {saving ? 'A guardar…' : 'Guardar'}</button><button className="dangerButton" onClick={() => void remove()}><Trash2 size={17}/> Apagar</button></div></header>
    {error && <div className="errorState">{error}</div>}

    <section className="playerHeroSection">
      <div className="playerHeroVisual">
        <div className="playerPortrait">{player.photoPath ? <img src={player.photoPath} alt={`Fotografia de ${player.displayName}`} /> : <span>{initials || 'AT'}</span>}<label className="photoEditButton" title="Alterar fotografia"><Camera size={16}/><input type="file" accept="image/*" onChange={e => void changePhoto(e.target.files?.[0])}/></label></div>
        <div className="playerHeroCopy"><span className="eyebrow">FICHA DE ATLETA · ANDEBOL</span><h1>{player.displayName}</h1><div className="playerMeta"><span>{team?.name ?? 'Sem equipa'}</span><span>{season?.name ?? 'Sem época'}</span><span>{player.position ?? 'Sem posição'}</span>{player.shirtNumber ? <span>#{player.shirtNumber}</span> : null}</div><p>Perfil competitivo com o HPI oficial do Andebol-Stats como único índice de pontuação. O vídeo complementa os eventos, mas não cria outro HPI.</p></div>
        <div className="playerHeroHpi"><span>HPI</span><strong>{hpi ? hpi.score : '—'}</strong><small>{hpiLabel}</small>{hpi?.updatedAt && <small>Atualizado {new Date(hpi.updatedAt).toLocaleDateString('pt-PT')}</small>}</div>
      </div>
      <div className="playerKpiGrid">{statItems.map(([label, value]) => <div className="statCard" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
    </section>

    <section className="section"><div className="sectionHeader"><div><h2>HPI · Análise de ações</h2><p>Único sistema de pontuação: pesos positivos e negativos definidos no Andebol-Stats.</p></div><Activity size={24}/></div><div className="explorerGrid"><div className="explorerCard"><span>HPI</span><strong>{hpi ? hpi.score : '—'}</strong><small>{hpi ? `Fonte: ${hpi.source} · ${hpi.version}` : 'Será preenchido pelo Andebol-Stats.'}</small></div><div className="explorerCard"><span>Positivo</span><strong>{hpi ? `+${hpi.positivePoints ?? 0}` : '—'}</strong><small>{hpi ? `${hpi.positiveActions ?? 0} ações` : 'Sem dados'}</small></div><div className="explorerCard"><span>Negativo</span><strong>{hpi ? `${hpi.negativePoints ?? 0}` : '—'}</strong><small>{hpi ? `${hpi.negativeActions ?? 0} ações` : 'Sem dados'}</small></div><div className="explorerCard"><span>Ritmo HPI</span><strong>{hpi?.ratePer60 != null ? hpi.ratePer60.toFixed(1) : '—'}</strong><small>pontos por 60 min, apenas para contextualização</small></div></div><div className="localList" style={{marginTop:12}}>{hpiTrend !== null && <div className="localRow"><div><strong>Tendência</strong><span>{hpiTrend > 0 ? '↑' : hpiTrend < 0 ? '↓' : '→'} {hpiTrend > 0 ? '+' : ''}{hpiTrend} pontos vs. último registo</span></div><span>{hpiHistory.length} registos HPI</span></div>}{hpi && <div className="localRow"><div><strong>Integridade do índice</strong><span>O HPI é recebido do Andebol-Stats; o Performance OS não altera os pesos.</span></div><span>{hpi.sampleSize ?? 1} jogo(s)</span></div>}</div></section>

    <section className="section"><div className="sectionHeader"><div><h2>Performance Explorer</h2><p>Contexto adicional ao HPI, sem criar um segundo índice.</p></div><Activity size={24}/></div><div className="explorerGrid"><div className="explorerCard"><span>HPI</span><strong>{hpi ? hpi.score : '—'}</strong><small>Índice oficial Andebol-Stats</small></div><div className="explorerCard"><span>Eficiência ofensiva</span><strong>{stats.shots ? `${Math.round((stats.goals / stats.shots) * 100)}%` : '—'}</strong><small>Golos / remates registados</small></div><div className="explorerCard"><span>Disciplina</span><strong>{stats.yellowCards + stats.redCards}</strong><small>Cartões acumulados</small></div><div className="explorerCard"><span>Volume de jogo</span><strong>{stats.events}</strong><small>Eventos individuais registados</small></div></div></section>

    <section className="section"><div className="sectionHeader"><div><h2>Perfil desportivo</h2><p>Informação base e identificação do atleta.</p></div><UserRound size={24}/></div><div className="localForm"><label>Nome<input value={player.firstName} onChange={e => update('firstName', e.target.value)}/></label><label>Apelido<input value={player.lastName} onChange={e => update('lastName', e.target.value)}/></label><label>Data de nascimento<input type="date" value={player.birthDate ?? ''} onChange={e => update('birthDate', e.target.value || undefined)}/></label><label>Número<input type="number" min="1" max="99" value={player.shirtNumber ?? ''} onChange={e => update('shirtNumber', e.target.value ? Number(e.target.value) : undefined)}/></label><label>Posição<select value={player.position ?? ''} onChange={e => update('position', e.target.value ? e.target.value as Position : undefined)}><option value="">Sem posição</option>{positions.map(position => <option key={position}>{position}</option>)}</select></label><label>Mão dominante<select value={player.hand ?? ''} onChange={e => update('hand', e.target.value ? e.target.value as Player['hand'] : undefined)}><option value="">Não definida</option><option value="RIGHT">Direita</option><option value="LEFT">Esquerda</option><option value="BOTH">Ambas</option></select></label></div></section>

    <section className="section"><div className="sectionHeader"><div><h2>Equipas e épocas</h2><p>Ligações atualmente registadas.</p></div><Shield size={24}/></div><div className="localList">{relations.length === 0 && <div className="emptyState"><strong>Sem ligações</strong><span>Esta atleta ainda não está associada a uma equipa/época.</span></div>}{relations.map(relation => { const linkedTeam = teams.find(item => item.id === relation.teamId); const linkedSeason = seasons.find(item => item.id === relation.seasonId); return <div className="localRow" key={relation.id}>{linkedTeam?.logoPath ? <img className="miniLogo" src={linkedTeam.logoPath} alt=""/> : null}<strong>{linkedTeam?.name ?? 'Equipa desconhecida'}</strong><span>{linkedSeason?.name ?? 'Época desconhecida'} · {relation.position ?? 'Sem posição'}{relation.shirtNumber ? ` · #${relation.shirtNumber}` : ''}</span></div> })}</div></section>
  </main>
}
