'use client'

import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import { Plus, Trash2, Swords, ArrowLeft, Save } from 'lucide-react'
import { db } from '../../src/lib/storage/db'
import { createId } from '../../src/lib/storage/id'
import type { Competition, Match, MatchSquad, Player, PlayerTeamSeason, Season, Team } from '../../src/lib/storage/types'
import '../dashboard.css'

export default function GamesPage() {
  const [matches, setMatches] = useState<Match[]>([]); const [teams, setTeams] = useState<Team[]>([]); const [seasons, setSeasons] = useState<Season[]>([]); const [competitions, setCompetitions] = useState<Competition[]>([])
  const [teamId, setTeamId] = useState(''); const [seasonId, setSeasonId] = useState(''); const [competitionId, setCompetitionId] = useState(''); const [opponent, setOpponent] = useState(''); const [date, setDate] = useState(''); const [venue, setVenue] = useState(''); const [homeAway, setHomeAway] = useState<Match['homeAway']>('HOME')
  const [selectedMatchId, setSelectedMatchId] = useState<string | null>(null); const [players, setPlayers] = useState<Player[]>([]); const [relations, setRelations] = useState<PlayerTeamSeason[]>([]); const [squad, setSquad] = useState<MatchSquad[]>([]); const [saved, setSaved] = useState(false)

  async function load() {
    if (!db) return
    const database = db
    const [nextMatches, nextTeams, nextSeasons, nextCompetitions] = await Promise.all([database.matches.orderBy('date').reverse().toArray(), database.teams.orderBy('name').toArray(), database.seasons.orderBy('name').reverse().toArray(), database.competitions.orderBy('name').toArray()])
    setMatches(nextMatches); setTeams(nextTeams); setSeasons(nextSeasons); setCompetitions(nextCompetitions); if (!teamId && nextTeams[0]) setTeamId(nextTeams[0].id); if (!seasonId && nextSeasons[0]) setSeasonId(nextSeasons[0].id)
  }
  useEffect(() => { void load() }, [])
  const seasonCompetitions = useMemo(() => competitions.filter(c => !seasonId || c.seasonId === seasonId), [competitions, seasonId])

  async function openMatch(id: string) {
    if (!db) return
    const database = db
    const m = await database.matches.get(id); if (!m) return
    const [p, r, sq] = await Promise.all([database.players.orderBy('displayName').toArray(), database.playerTeamSeasons.where('[teamId+seasonId]').equals([m.teamId, m.seasonId]).toArray(), database.matchSquads.where('matchId').equals(id).toArray()])
    setSelectedMatchId(id); setPlayers(p); setRelations(r); setSquad(sq); setSaved(true)
  }
  const selectedMatch = matches.find(m => m.id === selectedMatchId) ?? null
  const eligible = useMemo(() => { const ids = new Set(relations.map(r => r.playerId)); return players.filter(p => ids.has(p.id) && p.active) }, [players, relations])
  const current = (id: string) => squad.find(s => s.playerId === id)
  function toggle(player: Player) { const s = current(player.id); if (s) setSquad(squad.filter(x => x.playerId !== player.id)); else { const r = relations.find(x => x.playerId === player.id); setSquad([...squad, { id: createId(), matchId: selectedMatchId!, playerId: player.id, starter: false, captain: false, shirtNumber: r?.shirtNumber ?? player.shirtNumber, position: r?.position ?? player.position }]) } setSaved(false) }
  function setField(playerId: string, field: 'starter' | 'captain') { setSquad(squad.map(s => s.playerId === playerId ? { ...s, [field]: !s[field] } : field === 'captain' && s.captain ? { ...s, captain: false } : s)); setSaved(false) }
  async function saveSquad() { if (!db || !selectedMatchId) return; const database = db; await database.transaction('rw', database.matchSquads, async () => { await database.matchSquads.where('matchId').equals(selectedMatchId).delete(); if (squad.length) await database.matchSquads.bulkAdd(squad) }); setSaved(true) }
  async function add(e: React.FormEvent) { e.preventDefault(); if (!db || !teamId || !seasonId || !opponent.trim() || !date) return; const database = db; const now = new Date().toISOString(); await database.matches.add({ id: createId(), seasonId, competitionId: competitionId || undefined, teamId, opponentName: opponent.trim(), date, venue: venue.trim() || undefined, homeAway, status: 'PLANNED', createdAt: now, updatedAt: now }); setOpponent(''); setDate(''); setVenue(''); await load() }
  async function remove(id: string) { if (db && window.confirm('Apagar este jogo?')) { const database = db; await database.matches.delete(id); await load(); if (selectedMatchId === id) setSelectedMatchId(null) } }
  const teamName = (id: string) => teams.find(t => t.id === id)?.name ?? 'Equipa'; const seasonName = (id: string) => seasons.find(s => s.id === id)?.name ?? 'Época'; const competitionName = (id?: string) => id ? competitions.find(c => c.id === id)?.name : undefined

  if (selectedMatch) return <main className="content standalonePage"><header className="topbar"><div><button onClick={() => setSelectedMatchId(null)}><ArrowLeft size={16}/> Voltar aos jogos</button><p className="eyebrow">FICHA DO JOGO</p><h1>{teamName(selectedMatch.teamId)} vs {selectedMatch.opponentName}</h1><p>{seasonName(selectedMatch.seasonId)}{competitionName(selectedMatch.competitionId) ? ` · ${competitionName(selectedMatch.competitionId)}` : ''} · {new Date(selectedMatch.date).toLocaleString('pt-PT')} · {selectedMatch.homeAway === 'HOME' ? 'Casa' : selectedMatch.homeAway === 'AWAY' ? 'Fora' : 'Neutro'}</p></div></header><section className="section"><div className="sectionHeader"><div><p className="eyebrow">CONVOCATÓRIA</p><h2>Jogadores do jogo</h2><p>Seleciona os jogadores disponíveis e define titulares e capitão.</p></div><button onClick={() => void saveSquad()}><Save size={17}/> {saved ? 'Guardado' : 'Guardar convocatória'}</button></div>{eligible.length === 0 ? <div className="emptyState"><strong>Nenhum jogador elegível</strong><span>Adiciona jogadores à equipa e época em Gestão antes de os convocar.</span></div> : <div className="localList">{eligible.map(player => { const s = current(player.id); return <article className="localRow" key={player.id} style={{ display: 'grid', gridTemplateColumns: '1fr auto auto', gap: 12, alignItems: 'center' }}><label style={{ display: 'flex', gap: 10, alignItems: 'center' }}><input type="checkbox" checked={!!s} onChange={() => toggle(player)}/><span><strong>{player.displayName}</strong><small style={{ display: 'block', opacity: .7 }}>{player.position ?? '—'} · #{s?.shirtNumber ?? player.shirtNumber ?? '—'}</small></span></label><label>Inicial <input type="checkbox" disabled={!s} checked={!!s?.starter} onChange={() => setField(player.id, 'starter')}/></label><label>Capitão <input type="checkbox" disabled={!s} checked={!!s?.captain} onChange={() => setField(player.id, 'captain')}/></label></article> })}</div>}</section><section className="section"><p className="eyebrow">PRÓXIMO</p><h2>Live Match</h2><p>A codificação ao vivo será ativada depois de a convocatória estar definida.</p></section></main>

  return <main className="content standalonePage"><header className="topbar"><div><p className="eyebrow">CALENDÁRIO</p><h1>Jogos</h1><p>Planeamento dos jogos com dados guardados localmente.</p></div></header><section className="section"><form onSubmit={add} className="localForm"><select value={teamId} onChange={e => setTeamId(e.target.value)} required><option value="">Equipa</option>{teams.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select><select value={seasonId} onChange={e => { setSeasonId(e.target.value); setCompetitionId('') }} required><option value="">Época</option>{seasons.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select><select value={competitionId} onChange={e => setCompetitionId(e.target.value)}><option value="">Competição (opcional)</option>{seasonCompetitions.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select><input value={opponent} onChange={e => setOpponent(e.target.value)} placeholder="Adversário" required/><input value={date} onChange={e => setDate(e.target.value)} type="datetime-local" required/><input value={venue} onChange={e => setVenue(e.target.value)} placeholder="Pavilhão / local"/><select value={homeAway} onChange={e => setHomeAway(e.target.value as Match['homeAway'])}><option value="HOME">Casa</option><option value="AWAY">Fora</option><option value="NEUTRAL">Neutro</option></select><button type="submit"><Plus size={17}/> Criar jogo</button></form><div className="localList">{matches.length === 0 && <div className="emptyState"><Swords size={30}/><strong>Nenhum jogo</strong><span>Cria o primeiro jogo para começar a organizar a época.</span></div>}{matches.map(m => <article className="localRow" key={m.id}><button onClick={() => void openMatch(m.id)} style={{ flex: 1, textAlign: 'left', background: 'transparent', border: 0 }}><strong>{teamName(m.teamId)} vs {m.opponentName}</strong><span>{seasonName(m.seasonId)}{competitionName(m.competitionId) ? ` · ${competitionName(m.competitionId)}` : ''} · {new Date(m.date).toLocaleString('pt-PT')} · {m.homeAway === 'HOME' ? 'Casa' : m.homeAway === 'AWAY' ? 'Fora' : 'Neutro'} · {m.venue || 'Local por definir'}</span></button><button className="iconButton" onClick={() => remove(m.id)} aria-label="Apagar jogo"><Trash2 size={17}/></button></article>)}</div></section></main>
}
