'use client'

import { useEffect, useRef, useState } from 'react'
import { Film, Upload, Play, Pause, Plus, Clock3, Trash2, Download, Scissors, Save } from 'lucide-react'
import { db } from '../../src/lib/storage/db'
import { createId } from '../../src/lib/storage/id'
import type { MatchEvent, Clip, Player } from '../../src/lib/storage/types'
import { codingActions } from './coding'
import { createClipFromEvent, listMatchClips } from '../../src/lib/storage/clip-service'
import { updateMatchEvent, getMatchPlayers } from '../../src/lib/storage/event-repository'
import { shotZones, distances, shotTypes, results, attackPhases } from '../../src/lib/storage/handball-coding'
import '../dashboard.css'

function formatTime(seconds: number) { const total = Math.max(0, Math.floor(seconds)); return `${Math.floor(total / 60).toString().padStart(2,'0')}:${(total % 60).toString().padStart(2,'0')}` }

type Draft = { playerId?: string; zone?: string; distance?: string; shotType?: string; result?: string; attackPhase?: string; notes?: string }

export default function VideoAnalysisPage() {
  const inputRef = useRef<HTMLInputElement>(null); const videoRef = useRef<HTMLVideoElement>(null)
  const [videoUrl,setVideoUrl]=useState<string|null>(null); const [fileName,setFileName]=useState('Nenhum vídeo selecionado')
  const [matchId,setMatchId]=useState(''); const [matches,setMatches]=useState<{id:string;opponentName:string;date:string}[]>([])
  const [players,setPlayers]=useState<Player[]>([]); const [events,setEvents]=useState<MatchEvent[]>([]); const [clips,setClips]=useState<Clip[]>([])
  const [currentTime,setCurrentTime]=useState(0); const [playing,setPlaying]=useState(false); const [editing,setEditing]=useState<string|null>(null); const [draft,setDraft]=useState<Draft>({})

  useEffect(()=>{ if(!db)return; db.matches.orderBy('date').reverse().toArray().then(rows=>{setMatches(rows);if(rows[0])setMatchId(rows[0].id)}) },[])
  async function load(id=matchId){if(!db||!id)return;setEvents(await db.events.where('matchId').equals(id).sortBy('timestampSeconds'));setClips(await listMatchClips(id));setPlayers(await getMatchPlayers(id))}
  useEffect(()=>{load()},[matchId]); useEffect(()=>()=>{if(videoUrl)URL.revokeObjectURL(videoUrl)},[videoUrl])
  function selectVideo(file?:File){if(!file)return;setVideoUrl(old=>{if(old)URL.revokeObjectURL(old);return URL.createObjectURL(file)});setFileName(file.name);setPlaying(false);setCurrentTime(0)}
  function togglePlay(){const v=videoRef.current;if(!v)return;if(v.paused)v.play().catch(()=>undefined);else v.pause()}
  async function addEvent(type:string){if(!db||!matchId)return;const timestampSeconds=videoRef.current?.currentTime??currentTime;const event:MatchEvent={id:createId(),matchId,timestampSeconds,type,createdAt:new Date().toISOString()};await db.events.add(event);setEvents(prev=>[...prev,event].sort((a,b)=>a.timestampSeconds-b.timestampSeconds));setEditing(event.id);setDraft({})}
  function openEditor(event:MatchEvent){setEditing(event.id);setDraft({playerId:event.playerId,zone:event.zone,distance:event.distance,shotType:event.shotType,result:event.result,attackPhase:event.attackPhase,notes:event.notes})}
  async function saveEditor(){if(!editing)return;const updated=await updateMatchEvent(editing,draft);setEvents(prev=>prev.map(e=>e.id===updated.id?updated:e));setEditing(null)}
  async function makeClip(id:string){const clip=await createClipFromEvent(id,5,5);setClips(prev=>[...prev,clip].sort((a,b)=>a.startSeconds-b.startSeconds))}
  async function removeEvent(id:string){if(!db)return;await db.events.delete(id);await db.clips.where('eventId').equals(id).delete();setEvents(prev=>prev.filter(e=>e.id!==id));setClips(prev=>prev.filter(c=>c.eventId!==id));if(editing===id)setEditing(null)}
  function jumpTo(s:number){if(!videoRef.current)return;videoRef.current.currentTime=s;setCurrentTime(s)}
  function exportEvents(){const blob=new Blob([JSON.stringify(events,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${fileName.replace(/\.[^.]+$/,'')||'jogo'}-eventos.json`;a.click();URL.revokeObjectURL(url)}
  return <main className="content standalonePage"><header className="topbar"><div><p className="eyebrow">ANÁLISE</p><h1>Video Analysis</h1></div></header>
    <section className="section"><div className="localForm"><button onClick={()=>inputRef.current?.click()}><Upload size={17}/> Abrir vídeo local</button><input ref={inputRef} type="file" accept="video/*" hidden onChange={e=>selectVideo(e.target.files?.[0])}/><select value={matchId} onChange={e=>setMatchId(e.target.value)}><option value="">Selecionar jogo</option>{matches.map(m=><option key={m.id} value={m.id}>{new Date(m.date).toLocaleDateString('pt-PT')} · vs {m.opponentName}</option>)}</select><span style={{alignSelf:'center',fontSize:12,color:'#657086'}}>{fileName}</span><button onClick={exportEvents} disabled={!events.length}><Download size={16}/> Exportar eventos</button></div></section>
    <section className="section videoWorkspace"><div className="videoPanel">{videoUrl?<><video ref={videoRef} src={videoUrl} controls onTimeUpdate={e=>setCurrentTime(e.currentTarget.currentTime)} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} style={{width:'100%',maxHeight:520,background:'#090d14'}}/><div className="videoControls"><button onClick={togglePlay}>{playing?<Pause size={16}/>:<Play size={16}/>} {playing?'Pausa':'Reproduzir'}</button><span><Clock3 size={15}/> {formatTime(currentTime)} · Eventos: {events.length} · Clips: {clips.length}</span></div></>:<div className="videoEmpty"><Film size={42}/><strong>Vídeo local</strong><span>O vídeo é lido diretamente do teu computador.</span><button onClick={()=>inputRef.current?.click()}><Upload size={16}/> Selecionar vídeo</button></div>}</div>
      <aside className="codingPanel"><div className="sectionHeader"><div><p className="eyebrow">CODING</p><h3>Eventos</h3></div><span className="status">IndexedDB · Local</span></div><div className="codingButtons">{codingActions.map(a=><button key={a.id} onClick={()=>addEvent(a.id)} disabled={!matchId}><Plus size={14}/>{a.label}</button>)}</div><div className="localList">{events.length===0?<div className="emptyState"><span>Seleciona um jogo e regista o primeiro evento.</span></div>:events.map(e=><article className="localRow" key={e.id}><button style={{all:'unset',cursor:'pointer',flex:1}} onClick={()=>{jumpTo(e.timestampSeconds);openEditor(e)}}><div><strong>{codingActions.find(a=>a.id===e.type)?.label??e.type}</strong><span>{formatTime(e.timestampSeconds)} {e.playerId?'· jogadora associada':''}</span></div></button><button className="iconButton" onClick={()=>makeClip(e.id)} title="Criar clip"><Scissors size={16}/></button><button className="iconButton" onClick={()=>removeEvent(e.id)}><Trash2 size={16}/></button></article>)}</div></aside></section>
    {editing&&<section className="section editorCard"><div className="sectionHeader"><div><p className="eyebrow">DETALHE DO EVENTO</p><h3>Editar evento</h3></div><span className="status">Guardado localmente</span></div><div className="editorGrid"><label>Jogadora<select value={draft.playerId??''} onChange={e=>setDraft({...draft,playerId:e.target.value||undefined})}><option value="">Selecionar</option>{players.map(p=><option key={p.id} value={p.id}>{p.displayName}</option>)}</select></label><label>Zona<select value={draft.zone??''} onChange={e=>setDraft({...draft,zone:e.target.value||undefined})}><option value="">—</option>{shotZones.map(v=><option key={v}>{v}</option>)}</select></label><label>Distância<select value={draft.distance??''} onChange={e=>setDraft({...draft,distance:e.target.value||undefined})}><option value="">—</option>{distances.map(v=><option key={v}>{v}</option>)}</select></label><label>Tipo<select value={draft.shotType??''} onChange={e=>setDraft({...draft,shotType:e.target.value||undefined})}><option value="">—</option>{shotTypes.map(v=><option key={v}>{v}</option>)}</select></label><label>Resultado<select value={draft.result??''} onChange={e=>setDraft({...draft,result:e.target.value||undefined})}><option value="">—</option>{results.map(v=><option key={v}>{v}</option>)}</select></label><label>Fase<select value={draft.attackPhase??''} onChange={e=>setDraft({...draft,attackPhase:e.target.value||undefined})}><option value="">—</option>{attackPhases.map(v=><option key={v}>{v}</option>)}</select></label><label className="wide">Notas<textarea value={draft.notes??''} onChange={e=>setDraft({...draft,notes:e.target.value})} placeholder="Observações..."/></label></div><button className="saveButton" onClick={saveEditor}><Save size={16}/> Guardar evento</button></section>}
    <section className="section"><div className="sectionHeader"><div><p className="eyebrow">CLIPS</p><h3>Clips marcados</h3></div><span className="status">Pré-roll 5s · Pós-roll 5s</span></div><div className="localList">{clips.length===0?<div className="emptyState"><Scissors size={28}/><strong>Ainda não existem clips</strong><span>Usa a tesoura num evento para criar a marcação.</span></div>:clips.map(c=><article className="localRow" key={c.id}><button style={{all:'unset',cursor:'pointer',flex:1}} onClick={()=>jumpTo(c.startSeconds)}><div><strong>{c.title}</strong><span>{formatTime(c.startSeconds)} → {formatTime(c.endSeconds)}</span></div></button></article>)}</div></section>
  </main>
}
